---
driver:
  name: docker
platforms:
  - name: ansible-role-git-1404
    image: ubuntu:14.04

  - name: ansible-role-git-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
    destroy: ../resources/destroy.yml
  inventory:
    group_vars:
      all:
        git_user: root
